# Generated by Django 3.1.4 on 2020-12-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_id', models.CharField(max_length=50)),
                ('friend_name', models.CharField(max_length=50)),
                ('friend_screen_name', models.CharField(max_length=50)),
                ('friend_location', models.CharField(max_length=50)),
                ('friend_followers_count', models.CharField(max_length=100)),
                ('friend_friend_count', models.CharField(max_length=100)),
                ('friend_listed_count', models.CharField(max_length=100)),
                ('friend_favourite_count', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=50)),
                ('tweet_data', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_tweet', models.CharField(max_length=255)),
            ],
        ),
    ]
