# Generated by Django 3.1.4 on 2020-12-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplinks', '0002_auto_20201214_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
    ]
