# Generated by Django 3.1.4 on 2020-12-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toplinks', '0003_auto_20201214_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_hashtag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
