# Generated by Django 3.1.4 on 2020-12-14 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toplinks', '0006_auto_20201214_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_user_id',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='tweet_user_name',
        ),
    ]
